@echo off
chcp 65001 >nul
ren "112 - Peaches  Cream.mp3" "112-peaches-cream.mp3"
ren "4Batz - act ii date  8.mp3" "4batz-act-ii-date-8.mp3"
ren "Anita Baker - Sweet Love.mp3" "anita-baker-sweet-love.mp3"
ren "Brandy - Have You Ever.mp3" "brandy-have-you-ever.mp3"
ren "Donell Jones - U Know Whats Up.mp3" "donell-jones-u-know-whats-up.mp3"
ren "Dru Hill - In My Bed.mp3" "dru-hill-in-my-bed.mp3"
ren "Earth Wind  Fire - Reasons.mp3" "earth-wind-fire-reasons.mp3"
ren "Ella Mai - Bood Up.mp3" "ella-mai-bood-up.mp3"
ren "Ella Mai - Trip.mp3" "ella-mai-trip.mp3"
ren "En Vogue - Dont Let Go (Love).mp3" "en-vogue-dont-let-go-love.mp3"
ren "Fridayy - When It Comes To You.mp3" "fridayy-when-it-comes-to-you.mp3"
ren "Jagged Edge - Where the Party At.mp3" "jagged-edge-where-the-party-at.mp3"
ren "Jazmine Sullivan - Pick Up Your Feelings.mp3" "jazmine-sullivan-pick-up-your-feelings.mp3"
ren "Jhené Aiko - Sativa.mp3" "jhene-aiko-sativa.mp3"
ren "Jhené Aiko - The Worst.mp3" "jhene-aiko-the-worst.mp3"
ren "Joe - I Wanna Know.mp3" "joe-i-wanna-know.mp3"
ren "Kehlani - After Hours.mp3" "kehlani-after-hours.mp3"
ren "Kehlani - Nights Like This.mp3" "kehlani-nights-like-this.mp3"
ren "Kiana Ledé - EX.mp3" "kiana-lede-ex.mp3"
ren "Leon Thomas - Snooze.mp3" "leon-thomas-snooze.mp3"
ren "Lloyd - You.mp3" "lloyd-you.mp3"
ren "Luther Vandross - Never Too Much.mp3" "luther-vandross-never-too-much.mp3"
ren "Marquan - Love Like This.mp3" "marquan-love-like-this.mp3"
ren "Monica - Angel of Mine.mp3" "monica-angel-of-mine.mp3"
ren "Next - Too Close.mp3" "next-too-close.mp3"
ren "Omarion - Ice Box.mp3" "omarion-ice-box.mp3"
ren "PARTYNEXTDOOR - Break from Toronto.mp3" "partynextdoor-break-from-toronto.mp3"
ren "Patti LaBelle - If Only You Knew.mp3" "patti-labelle-if-only-you-knew.mp3"
ren "SZA - The Anonymous Ones.mp3" "sza-the-anonymous-ones.mp3"
ren "Sade - By Your Side.mp3" "sade-by-your-side.mp3"
ren "Sade - Smooth Operator.mp3" "sade-smooth-operator.mp3"
ren "Smokey Robinson - Cruisin.mp3" "smokey-robinson-cruisin.mp3"
ren "Snoh Aalegra - I Want You Around.mp3" "snoh-aalegra-i-want-you-around.mp3"
ren "Teddy Pendergrass - Close the Door.mp3" "teddy-pendergrass-close-the-door.mp3"
ren "The Isley Brothers - Between the Sheets.mp3" "the-isley-brothers-between-the-sheets.mp3"
ren "Tory Lanez - Say It.mp3" "tory-lanez-say-it.mp3"
ren "Tory Lanez - The Color Violet.mp3" "tory-lanez-the-color-violet.mp3"
ren "Trey Songz - Na Na.mp3" "trey-songz-na-na.mp3"
ren "Victoria Monét - On My Mama.mp3" "victoria-monet-on-my-mama.mp3"
echo Todos los archivos fueron renombrados exitosamente.
pause
