Rename-Item -Path "112 - Peaches  Cream.mp3" -NewName "112-peaches-cream.mp3"
Rename-Item -Path "4Batz - act ii date  8.mp3" -NewName "4batz-act-ii-date-8.mp3"
Rename-Item -Path "Anita Baker - Sweet Love.mp3" -NewName "anita-baker-sweet-love.mp3"
Rename-Item -Path "Brandy - Have You Ever.mp3" -NewName "brandy-have-you-ever.mp3"
Rename-Item -Path "Donell Jones - U Know Whats Up.mp3" -NewName "donell-jones-u-know-whats-up.mp3"
Rename-Item -Path "Dru Hill - In My Bed.mp3" -NewName "dru-hill-in-my-bed.mp3"
Rename-Item -Path "Earth Wind  Fire - Reasons.mp3" -NewName "earth-wind-fire-reasons.mp3"
Rename-Item -Path "Ella Mai - Bood Up.mp3" -NewName "ella-mai-bood-up.mp3"
Rename-Item -Path "Ella Mai - Trip.mp3" -NewName "ella-mai-trip.mp3"
Rename-Item -Path "En Vogue - Dont Let Go (Love).mp3" -NewName "en-vogue-dont-let-go-love.mp3"
Rename-Item -Path "Fridayy - When It Comes To You.mp3" -NewName "fridayy-when-it-comes-to-you.mp3"
Rename-Item -Path "Jagged Edge - Where the Party At.mp3" -NewName "jagged-edge-where-the-party-at.mp3"
Rename-Item -Path "Jazmine Sullivan - Pick Up Your Feelings.mp3" -NewName "jazmine-sullivan-pick-up-your-feelings.mp3"
Rename-Item -Path "Jhené Aiko - Sativa.mp3" -NewName "jhene-aiko-sativa.mp3"
Rename-Item -Path "Jhené Aiko - The Worst.mp3" -NewName "jhene-aiko-the-worst.mp3"
Rename-Item -Path "Joe - I Wanna Know.mp3" -NewName "joe-i-wanna-know.mp3"
Rename-Item -Path "Kehlani - After Hours.mp3" -NewName "kehlani-after-hours.mp3"
Rename-Item -Path "Kehlani - Nights Like This.mp3" -NewName "kehlani-nights-like-this.mp3"
Rename-Item -Path "Kiana Ledé - EX.mp3" -NewName "kiana-lede-ex.mp3"
Rename-Item -Path "Leon Thomas - Snooze.mp3" -NewName "leon-thomas-snooze.mp3"
Rename-Item -Path "Lloyd - You.mp3" -NewName "lloyd-you.mp3"
Rename-Item -Path "Luther Vandross - Never Too Much.mp3" -NewName "luther-vandross-never-too-much.mp3"
Rename-Item -Path "Marquan - Love Like This.mp3" -NewName "marquan-love-like-this.mp3"
Rename-Item -Path "Monica - Angel of Mine.mp3" -NewName "monica-angel-of-mine.mp3"
Rename-Item -Path "Next - Too Close.mp3" -NewName "next-too-close.mp3"
Rename-Item -Path "Omarion - Ice Box.mp3" -NewName "omarion-ice-box.mp3"
Rename-Item -Path "PARTYNEXTDOOR - Break from Toronto.mp3" -NewName "partynextdoor-break-from-toronto.mp3"
Rename-Item -Path "Patti LaBelle - If Only You Knew.mp3" -NewName "patti-labelle-if-only-you-knew.mp3"
Rename-Item -Path "SZA - The Anonymous Ones.mp3" -NewName "sza-the-anonymous-ones.mp3"
Rename-Item -Path "Sade - By Your Side.mp3" -NewName "sade-by-your-side.mp3"
Rename-Item -Path "Sade - Smooth Operator.mp3" -NewName "sade-smooth-operator.mp3"
Rename-Item -Path "Smokey Robinson - Cruisin.mp3" -NewName "smokey-robinson-cruisin.mp3"
Rename-Item -Path "Snoh Aalegra - I Want You Around.mp3" -NewName "snoh-aalegra-i-want-you-around.mp3"
Rename-Item -Path "Teddy Pendergrass - Close the Door.mp3" -NewName "teddy-pendergrass-close-the-door.mp3"
Rename-Item -Path "The Isley Brothers - Between the Sheets.mp3" -NewName "the-isley-brothers-between-the-sheets.mp3"
Rename-Item -Path "Tory Lanez - Say It.mp3" -NewName "tory-lanez-say-it.mp3"
Rename-Item -Path "Tory Lanez - The Color Violet.mp3" -NewName "tory-lanez-the-color-violet.mp3"
Rename-Item -Path "Trey Songz - Na Na.mp3" -NewName "trey-songz-na-na.mp3"
Rename-Item -Path "Victoria Monét - On My Mama.mp3" -NewName "victoria-monet-on-my-mama.mp3"
